# Generated by Django 4.2.5 on 2023-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_movies_genre_movies_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
