# Generated by Django 4.2.5 on 2023-10-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_movies_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=2000)),
                ('Year', models.PositiveIntegerField(blank=True, null=True)),
                ('Actors', models.CharField(max_length=200)),
                ('pop_now', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=5000)),
                ('Genre', models.CharField(max_length=200)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
    ]
