# Generated by Django 4.2.5 on 2023-10-11 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviestowatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.movies')),
                ('movielist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.watchlist')),
                ('series1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.series')),
            ],
        ),
    ]
