# Generated by Django 4.2.5 on 2023-10-11 14:37

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_moviestowatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
